import { ruleTesterTs } from '../utils/ruleTester';
import { enforceUniqueCursorHeaders } from '../rules/enforce-unique-cursor-headers';

const RULE_NAME = 'enforce-unique-cursor-headers';

ruleTesterTs.run(RULE_NAME, enforceUniqueCursorHeaders, {
  valid: [
    {
      code: `
/**
 * @fileoverview User authentication utilities
 * @author BluMint Team
 */

import { something } from './dep';
export const validateUser = (userId: string) => userId.length > 0;
      `,
      filename: '/workspace/src/auth.ts',
    },
    {
      code: `
// @fileoverview Single line header
// @author BluMint

export const noop = () => {};
      `,
      filename: '/workspace/src/single-line.ts',
    },
    {
      code: `
/*
 * @fileoverview Multi line block format
 * @author BluMint
 */

const id = 'abc';
export const useId = () => id;
      `,
      filename: '/workspace/src/block-format.ts',
    },
    {
      code: `
/* eslint-disable */
// Copyright 2024 BluMint
/**
 * @fileoverview Utilities with mixed comments
 * @author BluMint
 */

export const withDisable = (value: any) => value;
      `,
      filename: '/workspace/src/mixed-comments.ts',
    },
    {
      code: `
/**
 * @fileoverview Main utilities
 * @author BluMint
 */

import './side-effect';

// Section header unrelated to cursor metadata
/**
 * @section helper docs
 */
export const helper = () => 1;
      `,
      filename: '/workspace/src/sectioned.ts',
    },
    {
      code: `
// auto-generated by tool
export const generated = () => 1;
      `,
      filename: '/workspace/src/generated.ts',
    },
    {
      code: `
// @ts-nocheck
/**
 * @fileoverview Header with directive above
 * @author BluMint
 */
export const withDirective = () => true;
      `,
      filename: '/workspace/src/with-directive.ts',
      options: [
        {
          allowSplitHeaders: false,
        },
      ],
    },
    {
      code: `
/**
 * @fileoverview Header fragment
 */
/**
 * @author BluMint
 */
export const splitAllowed = () => true;
      `,
      filename: '/workspace/src/split-default.ts',
    },
    {
      code: `
/**
 * @fileoverview Custom tag header
 * @since 2024-01-15
 */
export const customTags = () => null;
      `,
      filename: '/workspace/src/custom-tags.ts',
      options: [
        {
          requiredTags: ['@fileoverview', '@since'],
        },
      ],
    },
    {
      code: `
/**
 * @fileoverview Single block is fine
 */
export const singleBlock = () => 1;
      `,
      filename: '/workspace/src/no-split.ts',
      options: [
        {
          allowSplitHeaders: false,
        },
      ],
    },
    {
      code: `
/**
 * @fileoverview Definition file skipped
 */
declare const something: string;
      `,
      filename: '/workspace/types.d.ts',
    },
    {
      code: `
/**
 * @fileoverview JavaScript header
 */
module.exports = {};
      `,
      filename: '/workspace/src/file.js',
    },
    {
      code: `
/**
 * @fileoverview Works on Windows paths
 */
export const windows = () => null;
      `,
      filename: 'C:\\repo\\src\\windows-path.ts',
    },
  ],
  invalid: [
    {
      code: `
import { HttpsError } from '../errors/HttpsError';

export const validateUser = (userId: string) => {
  return !!userId;
};
      `,
      filename: '/workspace/src/missing-header.ts',
      errors: [
        {
          messageId: 'missingHeader',
        },
      ],
    },
    {
      code: `
/**
 * @fileoverview User authentication utilities
 * @author BluMint Team
 */

/**
 * @fileoverview User authentication utilities
 * @author BluMint Team
 */
export const validateUser = (userId: string) => userId.length > 0;
      `,
      filename: '/workspace/src/duplicate-header.ts',
      errors: [{ messageId: 'duplicateHeader' }],
      output: `
/**
 * @fileoverview User authentication utilities
 * @author BluMint Team
 */

export const validateUser = (userId: string) => userId.length > 0;
      `,
    },
    {
      code: `
// @fileoverview User authentication utilities
// @author BluMint Team
/**
 * @fileoverview Duplicate block header
 * @author BluMint Team
 */
export const duplicateMixed = () => true;
      `,
      filename: '/workspace/src/duplicate-mixed.ts',
      errors: [{ messageId: 'duplicateHeader' }],
      output: `
// @fileoverview User authentication utilities
// @author BluMint Team
export const duplicateMixed = () => true;
      `,
    },
    {
      code: `
import { utils } from './utils';

/**
 * @fileoverview Header placed too late
 * @author BluMint Team
 */
export const lateHeader = () => utils;
      `,
      filename: '/workspace/src/late-header.ts',
      errors: [{ messageId: 'missingHeader' }],
    },
    {
      code: `
/**
 * @fileoverview Fragment one
 */
/**
 * @author BluMint
 */
export const splitNotAllowed = () => true;
      `,
      filename: '/workspace/src/split-not-allowed.ts',
      options: [
        {
          allowSplitHeaders: false,
        },
      ],
      errors: [{ messageId: 'duplicateHeader' }],
      output: null,
    },
    {
      code: `
/**
 * @fileoverview User utilities
 */

/**
 * @fileoverview User utilities
 * @version 1.0.0
 */
export const partialDuplicate = () => null;
      `,
      filename: '/workspace/src/partial-duplicate.ts',
      errors: [{ messageId: 'duplicateHeader' }],
      output: `
/**
 * @fileoverview User utilities
 */

export const partialDuplicate = () => null;
      `,
    },
    {
      code: `
/**
 * @fileoverview Missing since tag
 */
export const strictTags = () => null;
      `,
      filename: '/workspace/src/strict-tags.ts',
      options: [
        {
          requiredTags: ['@fileoverview', '@since'],
        },
      ],
      errors: [{ messageId: 'missingHeader' }],
    },
    {
      code: `
// auto-generated by tool
export const generated = () => 1;
      `,
      filename: '/workspace/src/generated-required.ts',
      options: [
        {
          ignoreGeneratedFiles: false,
        },
      ],
      errors: [{ messageId: 'missingHeader' }],
    },
    {
      code: `
/**
 * @fileoverview Duplicate header before code
 */


/**
 * @fileoverview Second header block
 */
export const spacedDuplicate = () => null;
      `,
      filename: '/workspace/src/spaced-duplicate.ts',
      errors: [{ messageId: 'duplicateHeader' }],
      output: `
/**
 * @fileoverview Duplicate header before code
 */


export const spacedDuplicate = () => null;
      `,
    },
    {
      code: `
export const withTemplate = () => null;
      `,
      filename: '/workspace/src/template-missing.ts',
      options: [
        {
          headerTemplate: `/**
 * @fileoverview Added by fixer
 * @author BluMint
 */`,
        },
      ],
      errors: [{ messageId: 'missingHeader' }],
      output: `/**
 * @fileoverview Added by fixer
 * @author BluMint
 */


export const withTemplate = () => null;
      `,
    },
    {
      code: `
export const withTemplateNewline = () => null;
      `,
      filename: '/workspace/src/template-with-newline.ts',
      options: [
        {
          headerTemplate: `/**
 * @fileoverview Added by fixer with trailing newline
 */

`,
        },
      ],
      errors: [{ messageId: 'missingHeader' }],
      output: `/**
 * @fileoverview Added by fixer with trailing newline
 */


export const withTemplateNewline = () => null;
      `,
    },
    {
      code: '#!/usr/bin/env node',
      filename: '/workspace/src/shebang-script.ts',
      options: [
        {
          headerTemplate: `/**
 * @fileoverview Added by fixer
 */
`,
        },
      ],
      errors: [{ messageId: 'missingHeader' }],
      output: `#!/usr/bin/env node
/**
 * @fileoverview Added by fixer
 */

`,
    },
    {
      code: `
/**
 * @fileoverview First header
 */

/**
 * @fileoverview Second header
 */

/**
 * @fileoverview Third header
 */
export const multipleDuplicates = () => null;
      `,
      filename: '/workspace/src/multiple-duplicates.ts',
      errors: [{ messageId: 'duplicateHeader' }, { messageId: 'duplicateHeader' }],
      output: `
/**
 * @fileoverview First header
 */


export const multipleDuplicates = () => null;
      `,
    },
  ],
});
