import { Linter, Rule } from 'eslint';
import { ruleTesterTs } from '../utils/ruleTester';
import { enforceUniqueCursorHeaders } from '../rules/enforce-unique-cursor-headers';

const RULE_NAME = 'enforce-unique-cursor-headers';

ruleTesterTs.run(RULE_NAME, enforceUniqueCursorHeaders, {
  valid: [
    {
      code: `
/**
 * @fileoverview User authentication utilities
 * @author BluMint Team
 */

import { something } from './dep';
export const validateUser = (userId: string) => userId.length > 0;
      `,
      filename: '/workspace/src/auth.ts',
    },
    {
      code: `
// @fileoverview Single line header
// @author BluMint

export const noop = () => {};
      `,
      filename: '/workspace/src/single-line.ts',
    },
    {
      code: `
/*
 * @fileoverview Multi line block format
 * @author BluMint
 */

const id = 'abc';
export const useId = () => id;
      `,
      filename: '/workspace/src/block-format.ts',
    },
    {
      code: `
/* banner */
// Copyright 2024 BluMint
/**
 * @fileoverview Utilities with mixed comments
 * @author BluMint
 */

export const withDisable = (value: any) => value;
      `,
      filename: '/workspace/src/mixed-comments.ts',
    },
    {
      code: `
/**
 * @fileoverview Main utilities
 * @author BluMint
 */

import './side-effect';

// Section header unrelated to cursor metadata
/**
 * @section helper docs
 */
export const helper = () => 1;
      `,
      filename: '/workspace/src/sectioned.ts',
    },
    {
      code: `
// auto-generated by tool
export const generated = () => 1;
      `,
      filename: '/workspace/src/generated.ts',
    },
    {
      code: `
// @ts-nocheck
/**
 * @fileoverview Header with directive above
 * @author BluMint
 */
export const withDirective = () => true;
      `,
      filename: '/workspace/src/with-directive.ts',
      options: [
        {
          allowSplitHeaders: false,
        },
      ],
    },
    {
      code: `
/**
 * @format
 */
/**
 * @jest-environment jsdom
 */
/**
 * @fileoverview Header should ignore pragmas
 * @author BluMint
 */
export const withPragmas = () => true;
      `,
      filename: '/workspace/src/with-pragmas.ts',
    },
    {
      code: `
/**
 * @jsxRuntime automatic
 */
/**
 * @jsxImportSource react
 */
/**
 * @fileoverview Header should ignore JSX pragmas
 * @author BluMint
 */
export const withJsxPragmas = () => true;
      `,
      filename: '/workspace/src/with-jsx-pragmas.ts',
    },
    {
      code: `
/**
 * @fileoverview Header fragment
 */
/**
 * @author BluMint
 */
export const splitAllowed = () => true;
      `,
      filename: '/workspace/src/split-default.ts',
    },
    {
      code: `
/**
 * @fileoverview Custom tag header
 * @since 2024-01-15
 */
export const customTags = () => null;
      `,
      filename: '/workspace/src/custom-tags.ts',
      options: [
        {
          requiredTags: ['@fileoverview', '@since'],
        },
      ],
    },
    {
      code: `
/**
 * @fileoverview Single block is fine
 */
export const singleBlock = () => 1;
      `,
      filename: '/workspace/src/no-split.ts',
      options: [
        {
          allowSplitHeaders: false,
        },
      ],
    },
    {
      code: `
/**
 * @fileoverview Definition file skipped
 */
declare const something: string;
      `,
      filename: '/workspace/types.d.ts',
    },
    {
      code: `
/**
 * @fileoverview JavaScript header
 */
module.exports = {};
      `,
      filename: '/workspace/src/file.js',
    },
    {
      code: `
/**
 * @fileoverview Works on Windows paths
 */
export const windows = () => null;
      `,
      filename: 'C:\\repo\\src\\windows-path.ts',
    },

    // requiredPatterns is an inclusion filter whose default (**/*.{ts,tsx,js,jsx})
    // already matches every linted file, so it can only show an effect when
    // NARROWED to something the filename misses. Paired with invalid case
    // 'requiredPatterns still matching' below, which is the same header-less
    // file under the defaults.
    {
      code: `
import { helper } from './helper';

export const runTask = () => helper();
      `,
      filename: '/workspace/src/tasks/runTask.ts',
      options: [{ requiredPatterns: ['**/*.mjs'] }],
    },

    // excludedPatterns is the mirror: it only shows an effect when WIDENED.
    // Same file and code as the requiredPatterns pair, exempted from the other
    // side of the filter.
    {
      code: `
import { helper } from './helper';

export const runTask = () => helper();
      `,
      filename: '/workspace/src/tasks/runTask.ts',
      options: [{ excludedPatterns: ['**/*'] }],
    },

    // generatedMarkers widened to a project-specific marker. "codegen" is not
    // one of the defaults, so this file is reported without the option (see the
    // paired invalid case).
    {
      code: `
// Built by the codegen pipeline.
export const ROUTES = ['/home'];
      `,
      filename: '/workspace/src/generated/routes.ts',
      options: [{ generatedMarkers: ['codegen'] }],
    },
  ],
  invalid: [
    /**
     * `null` written out explicitly, which is both schema-legal for this option
     * and its documented default. `applyDefault` deep-merges the consumer's
     * options over the rule's before `create` runs, and its `deepMerge` treats
     * `null` as an object, so a null on both sides used to reach
     * `Object.keys(null)` and throw while LOADING the rule — aborting the lint
     * for the file and taking every other rule with it. The assertion is that
     * the rule still reports normally; the regression it pins is the run
     * surviving at all.
     */
    {
      code: `
import { HttpsError } from '../errors/HttpsError';

export const validateUser = (userId: string) => {
  return !!userId;
};
      `,
      filename: '/workspace/src/missing-header.ts',
      options: [{ headerTemplate: null }],
      errors: [{ messageId: 'missingHeader' }],
    },
    {
      code: `
import { HttpsError } from '../errors/HttpsError';

export const validateUser = (userId: string) => {
  return !!userId;
};
      `,
      filename: '/workspace/src/missing-header.ts',
      errors: [
        {
          messageId: 'missingHeader',
        },
      ],
    },
    {
      code: `
/**
 * @fileoverview User authentication utilities
 * @author BluMint Team
 */

/**
 * @fileoverview User authentication utilities
 * @author BluMint Team
 */
export const validateUser = (userId: string) => userId.length > 0;
      `,
      filename: '/workspace/src/duplicate-header.ts',
      errors: [{ messageId: 'duplicateHeader' }],
      output: `
/**
 * @fileoverview User authentication utilities
 * @author BluMint Team
 */

export const validateUser = (userId: string) => userId.length > 0;
      `,
    },
    {
      code: `
// @fileoverview User authentication utilities
// @author BluMint Team
/**
 * @fileoverview Duplicate block header
 * @author BluMint Team
 */
export const duplicateMixed = () => true;
      `,
      filename: '/workspace/src/duplicate-mixed.ts',
      errors: [{ messageId: 'duplicateHeader' }],
      output: `
// @fileoverview User authentication utilities
// @author BluMint Team
export const duplicateMixed = () => true;
      `,
    },
    {
      code: `
import { utils } from './utils';

/**
 * @fileoverview Header placed too late
 * @author BluMint Team
 */
export const lateHeader = () => utils;
      `,
      filename: '/workspace/src/late-header.ts',
      errors: [{ messageId: 'missingHeader' }],
    },
    {
      code: `
/**
 * @fileoverview Fragment one
 */
/**
 * @author BluMint
 */
export const splitNotAllowed = () => true;
      `,
      filename: '/workspace/src/split-not-allowed.ts',
      options: [
        {
          allowSplitHeaders: false,
        },
      ],
      errors: [{ messageId: 'splitHeaderFragment' }],
      output: null,
    },
    {
      code: `
/**
 * @author BluMint
 */
/**
 * @fileoverview Fragment two
 */
export const splitPreceding = () => true;
      `,
      filename: '/workspace/src/split-preceding.ts',
      options: [
        {
          allowSplitHeaders: false,
        },
      ],
      errors: [{ messageId: 'splitHeaderFragment' }],
      output: null,
    },
    {
      code: `
// @ts-nocheck
/**
 * @fileoverview Header with directive merged
 * @author BluMint
 */
export const directiveMerged = () => true;
      `,
      filename: '/workspace/src/directive-merged.ts',
      options: [
        {
          allowSplitHeaders: false,
          excludedAtDirectives: [],
        },
      ],
      errors: [{ messageId: 'splitHeaderFragment' }],
      output: null,
    },
    {
      code: `
/**
 * @fileoverview User utilities
 */

/**
 * @fileoverview User utilities
 * @version 1.0.0
 */
export const partialDuplicate = () => null;
      `,
      filename: '/workspace/src/partial-duplicate.ts',
      errors: [{ messageId: 'duplicateHeader' }],
      output: `
/**
 * @fileoverview User utilities
 */

export const partialDuplicate = () => null;
      `,
    },
    {
      code: `
/**
 * @fileoverview Missing since tag
 */
export const strictTags = () => null;
      `,
      filename: '/workspace/src/strict-tags.ts',
      options: [
        {
          requiredTags: ['@fileoverview', '@since'],
        },
      ],
      errors: [{ messageId: 'missingHeader' }],
    },
    {
      code: `
// auto-generated by tool
export const generated = () => 1;
      `,
      filename: '/workspace/src/generated-required.ts',
      options: [
        {
          ignoreGeneratedFiles: false,
        },
      ],
      errors: [{ messageId: 'missingHeader' }],
    },
    {
      code: `
/**
 * @fileoverview Duplicate header before code
 */


/**
 * @fileoverview Second header block
 */
export const spacedDuplicate = () => null;
      `,
      filename: '/workspace/src/spaced-duplicate.ts',
      errors: [{ messageId: 'duplicateHeader' }],
      output: `
/**
 * @fileoverview Duplicate header before code
 */


export const spacedDuplicate = () => null;
      `,
    },
    {
      code: `
export const withTemplate = () => null;
      `,
      filename: '/workspace/src/template-missing.ts',
      options: [
        {
          headerTemplate: `/**
 * @fileoverview Added by fixer
 * @author BluMint
 */`,
        },
      ],
      errors: [{ messageId: 'missingHeader' }],
      output: `/**
 * @fileoverview Added by fixer
 * @author BluMint
 */


export const withTemplate = () => null;
      `,
    },
    {
      code: `
export const withTemplateNewline = () => null;
      `,
      filename: '/workspace/src/template-with-newline.ts',
      options: [
        {
          headerTemplate: `/**
 * @fileoverview Added by fixer with trailing newline
 */

`,
        },
      ],
      errors: [{ messageId: 'missingHeader' }],
      output: `/**
 * @fileoverview Added by fixer with trailing newline
 */


export const withTemplateNewline = () => null;
      `,
    },
    // An empty template can never satisfy requiredTags, so inserting it would
    // leave the report standing and let the fix loop re-run forever.
    {
      code: 'export const emptyTemplate = () => null;',
      filename: '/workspace/src/template-empty.ts',
      options: [
        {
          headerTemplate: '',
        },
      ],
      errors: [{ messageId: 'missingHeader' }],
      output: null,
    },
    {
      code: 'export const a = 1;',
      filename: '/workspace/src/no-tag-template.ts',
      options: [
        {
          headerTemplate: '/** Copyright Acme Corp. */',
        },
      ],
      errors: [{ messageId: 'missingHeader' }],
      output: null,
    },
    {
      code: 'export const a = 1;',
      filename: '/workspace/src/partial-tag-template.ts',
      options: [
        {
          headerTemplate: '/**\n * @fileoverview Thing\n */\n',
          requiredTags: ['@fileoverview', '@owner'],
        },
      ],
      errors: [{ messageId: 'missingHeader' }],
      output: null,
    },
    // Inserting bare text would make the file unparseable.
    {
      code: 'export const a = 1;',
      filename: '/workspace/src/bare-text-template.ts',
      options: [
        {
          headerTemplate: '@fileoverview thing',
        },
      ],
      errors: [{ messageId: 'missingHeader' }],
      output: null,
    },
    {
      code: 'export const a = 1;',
      filename: '/workspace/src/trailing-code-template.ts',
      options: [
        {
          headerTemplate: '/** @fileoverview thing */ const injected = 1;',
        },
      ],
      errors: [{ messageId: 'missingHeader' }],
      output: null,
    },
    // Split templates only satisfy the rule when its own grouping accepts them:
    // with allowSplitHeaders false, each block stands alone and neither block
    // carries both tags.
    {
      code: 'export const a = 1;',
      filename: '/workspace/src/split-template-no-split.ts',
      options: [
        {
          allowSplitHeaders: false,
          requiredTags: ['@fileoverview', '@owner'],
          headerTemplate:
            '/**\n * @fileoverview Thing\n */\n/**\n * @owner team\n */\n',
        },
      ],
      errors: [{ messageId: 'missingHeader' }],
      output: null,
    },
    // A blank line between the blocks makes them non-adjacent, so they never
    // merge into one group even with allowSplitHeaders true.
    {
      code: 'export const a = 1;',
      filename: '/workspace/src/split-template-not-adjacent.ts',
      options: [
        {
          requiredTags: ['@fileoverview', '@owner'],
          headerTemplate:
            '/**\n * @fileoverview Thing\n */\n\n/**\n * @owner team\n */\n',
        },
      ],
      errors: [{ messageId: 'missingHeader' }],
      output: null,
    },
    {
      code: 'export const a = 1;',
      filename: '/workspace/src/line-comment-template.ts',
      options: [
        {
          headerTemplate: '// @fileoverview thing',
        },
      ],
      errors: [{ messageId: 'missingHeader' }],
      output: '// @fileoverview thing\n\nexport const a = 1;',
    },
    {
      code: 'export const a = 1;',
      filename: '/workspace/src/mixed-comment-template.ts',
      options: [
        {
          headerTemplate: '/** Copyright Acme Corp. */\n// @fileoverview thing',
        },
      ],
      errors: [{ messageId: 'missingHeader' }],
      output:
        '/** Copyright Acme Corp. */\n// @fileoverview thing\n\nexport const a = 1;',
    },
    {
      code: 'export const a = 1;',
      filename: '/workspace/src/multi-tag-template.ts',
      options: [
        {
          headerTemplate:
            '/**\n * @fileoverview Thing\n * @owner BluMint\n */\n',
          requiredTags: ['@fileoverview', '@owner'],
        },
      ],
      errors: [{ messageId: 'missingHeader' }],
      output:
        '/**\n * @fileoverview Thing\n * @owner BluMint\n */\n\nexport const a = 1;',
    },
    {
      code: '#!/usr/bin/env node',
      filename: '/workspace/src/shebang-script.ts',
      options: [
        {
          headerTemplate: `/**
 * @fileoverview Added by fixer
 */
`,
        },
      ],
      errors: [{ messageId: 'missingHeader' }],
      output: `#!/usr/bin/env node
/**
 * @fileoverview Added by fixer
 */

`,
    },
    {
      code: `
/**
 * @fileoverview First header
 */

/**
 * @fileoverview Second header
 */

/**
 * @fileoverview Third header
 */
export const multipleDuplicates = () => null;
      `,
      filename: '/workspace/src/multiple-duplicates.ts',
      errors: [
        { messageId: 'duplicateHeader' },
        { messageId: 'duplicateHeader' },
      ],
      output: `
/**
 * @fileoverview First header
 */


export const multipleDuplicates = () => null;
      `,
    },
    {
      code: `
/**
 * @fileoverview has fileoverview but missing since
 */
export const x = 1;
      `,
      filename: '/workspace/src/missing-tag-no-split.ts',
      options: [
        {
          allowSplitHeaders: false,
          requiredTags: ['@fileoverview', '@since'],
        },
      ],
      errors: [{ messageId: 'missingHeader' }],
    },

    // Option-dependence baseline for the requiredPatterns / excludedPatterns
    // valid cases above: identical file and code, no options. The defaults
    // include this .ts file and exclude nothing that matches it, so it reports.
    {
      code: `
import { helper } from './helper';

export const runTask = () => helper();
      `,
      filename: '/workspace/src/tasks/runTask.ts',
      errors: [{ messageId: 'missingHeader' }],
    },

    // excludedPatterns narrowed to nothing. A .d.ts file is exempt under the
    // default excludedPatterns (**/*.d.ts), so emptying the list is the only
    // reason this reports — the widening direction alone would not prove the
    // defaults are read.
    {
      code: `
import { helper } from './helper';

export const runTask = () => helper();
      `,
      filename: '/workspace/src/tasks/runTask.d.ts',
      options: [{ excludedPatterns: [] }],
      errors: [{ messageId: 'missingHeader' }],
    },

    // Option-dependence baseline for the generatedMarkers valid case: the same
    // "codegen" file with no option is not recognized as generated.
    {
      code: `
// Built by the codegen pipeline.
export const ROUTES = ['/home'];
      `,
      filename: '/workspace/src/generated/routes.ts',
      errors: [{ messageId: 'missingHeader' }],
    },

    // generatedMarkers narrowed to nothing. `@generated` is a default marker,
    // so this file is skipped without the option; emptying the list proves the
    // defaults are the source of the skip.
    {
      code: `
// @generated by protoc.
export const VERSION = 1;
      `,
      filename: '/workspace/src/generated/version.ts',
      options: [{ generatedMarkers: [] }],
      errors: [{ messageId: 'missingHeader' }],
    },
  ],
});

// Issue #1461: RuleTester applies a single fix pass, so it cannot show what
// `eslint --fix` actually writes. These cases run the real multi-pass loop and
// assert the invariant the bug violated: the header fixer removes its own
// trigger, so a template the rule would not accept is never inserted at all.
describe(`${RULE_NAME}: the header fixer must converge (issue #1461)`, () => {
  const RULE_ID = `@blumintinc/blumint/${RULE_NAME}`;
  const FILENAME = '/workspace/src/fix-loop.ts';
  const SOURCE = 'export const a = 1;\n';

  const createLinter = () => {
    const linter = new Linter();
    linter.defineParser(
      '@typescript-eslint/parser',
      // eslint-disable-next-line @typescript-eslint/no-var-requires
      require('@typescript-eslint/parser'),
    );
    linter.defineRule(
      RULE_ID,
      enforceUniqueCursorHeaders as unknown as Rule.RuleModule,
    );
    return linter;
  };

  const runFixLoop = (code: string, options: Record<string, unknown>) => {
    const linter = createLinter();
    const config = {
      parser: '@typescript-eslint/parser',
      parserOptions: {
        ecmaVersion: 2020 as const,
        sourceType: 'module' as const,
      },
      rules: { [RULE_ID]: ['error', options] as const },
    };
    const { output } = linter.verifyAndFix(code, config, {
      filename: FILENAME,
    });

    return {
      output,
      remaining: linter.verify(output, config, { filename: FILENAME }),
    };
  };

  it('inserts a conforming template exactly once and stops reporting', () => {
    const { output, remaining } = runFixLoop(SOURCE, {
      headerTemplate: '/**\n * @fileoverview Thing\n */\n',
    });

    expect(output).toBe(`/**\n * @fileoverview Thing\n */\n\n${SOURCE}`);
    expect(remaining).toHaveLength(0);
  });

  it('inserts a conforming line-comment template exactly once', () => {
    const { output, remaining } = runFixLoop(SOURCE, {
      headerTemplate: '// @fileoverview thing',
    });

    expect(output).toBe(`// @fileoverview thing\n\n${SOURCE}`);
    expect(remaining).toHaveLength(0);
  });

  it('leaves the source untouched when the template omits a required tag', () => {
    const { output, remaining } = runFixLoop(SOURCE, {
      headerTemplate: '/** Copyright Acme Corp. All rights reserved. */',
    });

    expect(output).toBe(SOURCE);
    expect(remaining.map((message) => message.messageId)).toEqual([
      'missingHeader',
    ]);
  });

  it('leaves the source untouched when the template satisfies only some required tags', () => {
    const { output, remaining } = runFixLoop(SOURCE, {
      headerTemplate: '/**\n * @fileoverview Thing\n */\n',
      requiredTags: ['@fileoverview', '@owner'],
    });

    expect(output).toBe(SOURCE);
    expect(remaining.map((message) => message.messageId)).toEqual([
      'missingHeader',
    ]);
  });

  it('leaves the source untouched for an empty template', () => {
    const { output, remaining } = runFixLoop(SOURCE, { headerTemplate: '' });

    expect(output).toBe(SOURCE);
    expect(remaining.map((message) => message.messageId)).toEqual([
      'missingHeader',
    ]);
  });

  // A template can carry every required tag and still fail the rule's own
  // detection, which groups comments before checking tags. Whether a template
  // converges therefore depends on allowSplitHeaders and block adjacency, not
  // on the template text alone.
  const SPLIT_TAGS = ['@fileoverview', '@owner'];
  const ADJACENT_BLOCKS =
    '/**\n * @fileoverview Thing\n */\n/**\n * @owner team\n */\n';
  const SEPARATED_BLOCKS =
    '/**\n * @fileoverview Thing\n */\n\n/**\n * @owner team\n */\n';
  const SINGLE_BLOCK = '/**\n * @fileoverview Thing\n * @owner team\n */\n';

  it('leaves the source untouched for split blocks when allowSplitHeaders is false', () => {
    const { output, remaining } = runFixLoop(SOURCE, {
      allowSplitHeaders: false,
      requiredTags: SPLIT_TAGS,
      headerTemplate: ADJACENT_BLOCKS,
    });

    expect(output).toBe(SOURCE);
    expect(remaining.map((message) => message.messageId)).toEqual([
      'missingHeader',
    ]);
  });

  it('leaves the source untouched for non-adjacent split blocks', () => {
    const { output, remaining } = runFixLoop(SOURCE, {
      requiredTags: SPLIT_TAGS,
      headerTemplate: SEPARATED_BLOCKS,
    });

    expect(output).toBe(SOURCE);
    expect(remaining.map((message) => message.messageId)).toEqual([
      'missingHeader',
    ]);
  });

  it('inserts a single block carrying every tag when allowSplitHeaders is false', () => {
    const { output, remaining } = runFixLoop(SOURCE, {
      allowSplitHeaders: false,
      requiredTags: SPLIT_TAGS,
      headerTemplate: SINGLE_BLOCK,
    });

    expect(output).toBe(`${SINGLE_BLOCK}\n${SOURCE}`);
    expect(remaining).toHaveLength(0);
  });

  it('inserts adjacent split blocks when allowSplitHeaders is true', () => {
    const { output, remaining } = runFixLoop(SOURCE, {
      requiredTags: SPLIT_TAGS,
      headerTemplate: ADJACENT_BLOCKS,
    });

    expect(output).toBe(`${ADJACENT_BLOCKS}\n${SOURCE}`);
    expect(remaining).toHaveLength(0);
  });

  // A template whose extra block trips a different diagnostic still converges:
  // splitHeaderFragment carries no fix, so the loop stops after one insertion.
  it('inserts an accepted template once even when a trailing block is reported', () => {
    const template = `${SINGLE_BLOCK}/**\n * @author BluMint\n */\n`;
    const { output, remaining } = runFixLoop(SOURCE, {
      allowSplitHeaders: false,
      requiredTags: SPLIT_TAGS,
      headerTemplate: template,
    });

    expect(output).toBe(`${template}\n${SOURCE}`);
    expect(remaining.map((message) => message.messageId)).toEqual([
      'splitHeaderFragment',
    ]);
  });

  it('never inserts a non-comment template, which would break parsing', () => {
    const { output, remaining } = runFixLoop(SOURCE, {
      headerTemplate: '@fileoverview thing',
    });

    expect(output).toBe(SOURCE);
    expect(remaining.map((message) => message.messageId)).toEqual([
      'missingHeader',
    ]);
    expect(
      remaining.some((message) => message.fatal || message.ruleId === null),
    ).toBe(false);
  });
});
