import { AST_NODE_TYPES, TSESLint, TSESTree } from '@typescript-eslint/utils';
import { createRule } from '../utils/createRule';

type MessageIds = 'preferTimestampNow';

const FIRESTORE_MODULES = new Set([
  'firebase-admin/firestore',
  'firebase/firestore',
]);

export const enforceTimestampNow = createRule<[], MessageIds>({
  name: 'enforce-timestamp-now',
  meta: {
    type: 'suggestion',
    docs: {
      description:
        'Enforce the use of Timestamp.now() for getting the current timestamp in backend code. This rule prevents using alternatives like Timestamp.fromDate(new Date()) or other date creation patterns that could lead to inconsistency.',
      recommended: 'error',
      requiresTypeChecking: false,
      extendsBaseRule: false,
    },
    fixable: 'code',
    schema: [],
    messages: {
      preferTimestampNow:
        '{{expression}} builds a timestamp from the local JS clock. Firestore timestamps should come from the SDK so they stay server-synced and avoid drift between app servers and clients. Use {{timestampAlias}}.now() so the timestamp is generated by Firestore; replace this expression with {{timestampAlias}}.now().',
    },
  },
  defaultOptions: [],
  create(context) {
    const sourceCode = context.getSourceCode();
    // Only apply this rule to backend code (functions/src/). Normalize Windows
    // backslash separators first so the forward-slash path check matches on
    // every platform — otherwise `getFilename()` returns `C:\repo\functions\
    // src\...` on Windows, the guard bails, and the rule silently enforces
    // nothing (issue #1266).
    const filename = context.getFilename().replace(/\\/g, '/');
    if (!filename.includes('functions/src/')) {
      return {};
    }

    // Skip test files
    if (filename.includes('.test.') || filename.includes('.spec.')) {
      return {};
    }

    // Names that may denote the Firestore `Timestamp` class when matching
    // `X.fromDate(new Date())` / `X.fromMillis(Date.now())`. Seeded with the
    // default name so detection still works when the class reaches the file
    // through a re-export or a `require()` the rule cannot see. Those reports
    // rewrite an expression whose object identifier is already written in the
    // source, so a seeded name can never produce an unbound reference.
    const timestampAliases = new Set<string>(['Timestamp']);

    // Names actually bound by an observed `Timestamp` import. Tracked apart
    // from `timestampAliases` because the `new Date()` fix synthesizes an
    // identifier the original code never mentions: with no real import the
    // rewrite emits an unbound `Timestamp` and turns compiling code into
    // TS2304 (issue #1521).
    const importedTimestampAliases: string[] = [];

    function recordTimestampAlias(localName: string): void {
      timestampAliases.add(localName);
      if (!importedTimestampAliases.includes(localName)) {
        importedTimestampAliases.push(localName);
      }
    }

    /** Local names a static Firestore import binds to `Timestamp`. */
    function staticTimestampAliases(
      node: TSESTree.ImportDeclaration,
    ): string[] {
      if (
        typeof node.source.value !== 'string' ||
        !FIRESTORE_MODULES.has(node.source.value)
      ) {
        return [];
      }
      return node.specifiers
        .filter(
          (specifier): specifier is TSESTree.ImportSpecifier =>
            specifier.type === AST_NODE_TYPES.ImportSpecifier &&
            specifier.imported.type === AST_NODE_TYPES.Identifier &&
            specifier.imported.name === 'Timestamp',
        )
        .map((specifier) => specifier.local.name);
    }

    /**
     * Local names a `const { Timestamp } = await import(...)` declarator binds
     * to `Timestamp`.
     */
    function dynamicTimestampAliases(
      node: TSESTree.VariableDeclarator,
    ): string[] {
      if (
        node.init?.type !== AST_NODE_TYPES.AwaitExpression ||
        node.init.argument.type !== AST_NODE_TYPES.ImportExpression ||
        node.id.type !== AST_NODE_TYPES.ObjectPattern
      ) {
        return [];
      }
      const source = node.init.argument.source;
      if (
        source.type !== AST_NODE_TYPES.Literal ||
        typeof source.value !== 'string' ||
        !FIRESTORE_MODULES.has(source.value)
      ) {
        return [];
      }
      const aliases: string[] = [];
      node.id.properties.forEach((prop) => {
        if (
          prop.type === AST_NODE_TYPES.Property &&
          prop.key.type === AST_NODE_TYPES.Identifier &&
          prop.key.name === 'Timestamp' &&
          prop.value.type === AST_NODE_TYPES.Identifier
        ) {
          aliases.push(prop.value.name);
        }
      });
      return aliases;
    }

    /** Whether a resolved binding is the Firestore `Timestamp` class itself. */
    function isTimestampImportBinding(
      variable: TSESLint.Scope.Variable,
    ): boolean {
      return variable.defs.some((def) => {
        if (def.node.type === AST_NODE_TYPES.ImportSpecifier) {
          const declaration = def.node.parent;
          return (
            declaration?.type === AST_NODE_TYPES.ImportDeclaration &&
            staticTimestampAliases(declaration).includes(variable.name)
          );
        }
        if (def.node.type === AST_NODE_TYPES.VariableDeclarator) {
          return dynamicTimestampAliases(def.node).includes(variable.name);
        }
        return false;
      });
    }

    /** The binding a name resolves to at the node currently being visited. */
    function resolveBinding(name: string): TSESLint.Scope.Variable | undefined {
      let scope: TSESLint.Scope.Scope | null = context.getScope();
      while (scope) {
        const binding = scope.variables.find(
          (variable) => variable.name === name,
        );
        if (binding) {
          return binding;
        }
        scope = scope.upper;
      }
      return undefined;
    }

    // A synthesized `Timestamp.now()` is only safe when the alias resolves to
    // the import at the rewrite site. Resolution has to run per name from the
    // innermost scope outward: an alias bound by a dynamic import inside another
    // function is unreachable here, and an inner binding of the same name would
    // capture the emitted reference and silently swap in a different value
    // (issues #1455/#1456).
    function findTimestampAliasInScope(): string | undefined {
      return importedTimestampAliases.find((alias) => {
        const binding = resolveBinding(alias);
        return !!binding && isTimestampImportBinding(binding);
      });
    }

    function isTimestampFromDateWithNewDate(
      node: TSESTree.CallExpression,
    ): boolean {
      // Check if it's a Timestamp.fromDate(new Date()) call
      if (node.callee.type === AST_NODE_TYPES.MemberExpression) {
        const property = node.callee.property;
        const object = node.callee.object;

        if (
          property.type === AST_NODE_TYPES.Identifier &&
          property.name === 'fromDate' &&
          object.type === AST_NODE_TYPES.Identifier &&
          timestampAliases.has(object.name)
        ) {
          // Check if the argument is new Date()
          const arg = node.arguments[0];
          if (
            arg &&
            arg.type === AST_NODE_TYPES.NewExpression &&
            arg.callee.type === AST_NODE_TYPES.Identifier &&
            arg.callee.name === 'Date' &&
            arg.arguments.length === 0
          ) {
            return true;
          }

          // Check if the argument is a variable reference to a Date object
          if (arg && arg.type === AST_NODE_TYPES.Identifier) {
            // If it's a variable, we need to check if it's a Date that's being modified
            // If it's modified, we shouldn't flag it
            return false;
          }
        }
      }
      return false;
    }

    function isTimestampFromMillisWithDateNow(
      node: TSESTree.CallExpression,
    ): boolean {
      // Check if it's a Timestamp.fromMillis(Date.now()) call
      if (node.callee.type === AST_NODE_TYPES.MemberExpression) {
        const property = node.callee.property;
        const object = node.callee.object;

        if (
          property.type === AST_NODE_TYPES.Identifier &&
          property.name === 'fromMillis' &&
          object.type === AST_NODE_TYPES.Identifier &&
          timestampAliases.has(object.name)
        ) {
          // Check if the argument is Date.now()
          const arg = node.arguments[0];
          if (
            arg &&
            arg.type === AST_NODE_TYPES.CallExpression &&
            arg.callee.type === AST_NODE_TYPES.MemberExpression &&
            arg.callee.object.type === AST_NODE_TYPES.Identifier &&
            arg.callee.object.name === 'Date' &&
            arg.callee.property.type === AST_NODE_TYPES.Identifier &&
            arg.callee.property.name === 'now'
          ) {
            return true;
          }
        }
      }
      return false;
    }

    function isNewDateDirectUsage(node: TSESTree.NewExpression): boolean {
      // Check if it's a new Date() with no arguments
      return (
        node.callee.type === AST_NODE_TYPES.Identifier &&
        node.callee.name === 'Date' &&
        node.arguments.length === 0
      );
    }

    // Check if a Date object is being modified (e.g., futureDate.setDate())
    function isDateBeingModified(dateVar: string): boolean {
      // Look through the scope to find if this variable is modified
      const scope = context.getScope();
      const variable = scope.variables.find((v) => v.name === dateVar);

      if (!variable) return false;

      // Check if any references to this variable are followed by property access and modification
      return variable.references.some((ref) => {
        const id = ref.identifier;
        const parent = id.parent;

        // Check for patterns like dateVar.setDate(), dateVar.setHours(), etc.
        return (
          parent &&
          parent.type === AST_NODE_TYPES.MemberExpression &&
          parent.object === id &&
          parent.property.type === AST_NODE_TYPES.Identifier &&
          (parent.property.name.startsWith('set') ||
            parent.property.name === 'toISOString' ||
            parent.property.name === 'toLocaleString' ||
            parent.property.name === 'toString')
        );
      });
    }

    return {
      Program(node): void {
        // Collect static imports before any usage is visited. An import is
        // hoisted and module-scoped, so it binds `Timestamp` for the whole file
        // regardless of where it sits; visiting imports in traversal order
        // would make the guard depend on the import preceding the usage.
        node.body.forEach((statement) => {
          if (statement.type === AST_NODE_TYPES.ImportDeclaration) {
            staticTimestampAliases(statement).forEach(recordTimestampAlias);
          }
        });
      },

      VariableDeclarator(node): void {
        // Track dynamic imports of Timestamp
        dynamicTimestampAliases(node).forEach(recordTimestampAlias);
      },

      CallExpression(node): void {
        if (isTimestampFromDateWithNewDate(node)) {
          if (node.callee.type !== AST_NODE_TYPES.MemberExpression) {
            return;
          }
          const timestampObj = sourceCode.getText(node.callee.object);
          context.report({
            node,
            messageId: 'preferTimestampNow',
            data: {
              expression: sourceCode.getText(node),
              timestampAlias: timestampObj,
            },
            fix(fixer) {
              if (node.callee.type === AST_NODE_TYPES.MemberExpression) {
                return fixer.replaceText(node, `${timestampObj}.now()`);
              }
              return null;
            },
          });
        } else if (isTimestampFromMillisWithDateNow(node)) {
          if (node.callee.type !== AST_NODE_TYPES.MemberExpression) {
            return;
          }
          const timestampObj = sourceCode.getText(node.callee.object);
          context.report({
            node,
            messageId: 'preferTimestampNow',
            data: {
              expression: sourceCode.getText(node),
              timestampAlias: timestampObj,
            },
            fix(fixer) {
              if (node.callee.type === AST_NODE_TYPES.MemberExpression) {
                return fixer.replaceText(node, `${timestampObj}.now()`);
              }
              return null;
            },
          });
        }
      },

      NewExpression(node): void {
        // Only flag direct new Date() usage if it's assigned to a variable named timestamp or similar
        if (isNewDateDirectUsage(node)) {
          const parent = node.parent;
          if (
            parent &&
            parent.type === AST_NODE_TYPES.VariableDeclarator &&
            parent.id.type === AST_NODE_TYPES.Identifier
          ) {
            const varName = parent.id.name.toLowerCase();

            // Check if the variable name suggests it's a timestamp
            if (
              varName.includes('timestamp') ||
              varName.includes('time') ||
              varName.includes('now') ||
              varName.includes('date') ||
              varName.includes('created') ||
              varName.includes('updated')
            ) {
              // Check if the Date object is being modified
              if (isDateBeingModified(parent.id.name)) {
                // If the Date is being modified, don't flag it
                return;
              }

              // Stay silent unless a real `Timestamp` binding is in scope. The
              // rewrite names an identifier the source never mentions, and a
              // file with no Firestore import is almost certainly using the
              // `Date` for something other than a Firestore document anyway.
              const timestampName = findTimestampAliasInScope();
              if (!timestampName) {
                return;
              }

              const expressionText = sourceCode.getText(node);
              context.report({
                node,
                messageId: 'preferTimestampNow',
                data: {
                  expression: expressionText,
                  timestampAlias: timestampName,
                },
                fix(fixer) {
                  return fixer.replaceText(node, `${timestampName}.now()`);
                },
              });
            }
          }
        }
      },
    };
  },
});
