image:
  file: .devcontainer/Dockerfile
  context: .devcontainer

tasks:
  - init: npm install
  # Add back in when we're doing more pythonic development
  # - command: pip3 install -r requirements.txt
  - command: git config pull.rebase false && git config rerere.enabled true && rm -f .git/hooks/prepare-commit-msg && npx opencommit hook set

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - mattpocock.ts-error-translator
    - Orta.vscode-jest
    - redhat.vscode-yaml
    - eamodio.gitlens
    - ambar.bundle-size
    - streetsidesoftware.code-spell-checker
