name: Deploy Changed Firebase Cloud Functions

on:
  pull_request:
    branches: [ develop, main ]
  push:
    branches: [ develop, main ]

jobs:
  detect-and-deploy-changed-functions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Need full history for comparing changes

      - name: Checkout Full
        uses: ./.github/actions/checkout-full
        with:
          dotenv-key: ${{ secrets.DOTENV_KEY }}
          blumint-development-sa: ${{ secrets.BLUMINT_DEVELOPMENT_SA }}
          blumint-production-sa: ${{ secrets.BLUMINT_PRODUCTION_SA }}
      
      - name: Set DOTENV_KEY in environment
        run: echo "DOTENV_KEY=${{ secrets.DOTENV_KEY }}" >> $GITHUB_ENV
        shell: bash

      - name: Get base commit
        id: get-base-commit
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "base_commit=${{ github.event.pull_request.base.sha }}" >> $GITHUB_OUTPUT
          else
            echo "base_commit=${{ github.event.before }}" >> $GITHUB_OUTPUT
          fi

      - name: Build current functions
        run: |
          npm run functions:build
          mv lib lib-current

      - name: Checkout base commit
        run: git checkout ${{ steps.get-base-commit.outputs.base_commit }}

      - name: Build base functions
        run: |
          npm run functions:build
          mv lib lib-base

      - name: Detect changed functions
        id: detect-changes
        run: |
          changed_functions=""
          
          # Go through each function in current build
          for current_func in lib-current/*/; do
            func_name=$(basename "$current_func")
            
            # Check if function exists in base
            if [ -d "lib-base/$func_name" ]; then
              # Compare package.json and index.js
              if ! cmp -s "lib-current/$func_name/package.json" "lib-base/$func_name/package.json" || \
                 ! cmp -s "lib-current/$func_name/index.js" "lib-base/$func_name/index.js"; then
                # Function has changed
                if [ -z "$changed_functions" ]; then
                  changed_functions="./$(echo $func_name | sed 's/-/\//g').f.ts"
                else
                  changed_functions="$changed_functions ./$(echo $func_name | sed 's/-/\//g').f.ts"
                fi
              fi
            else
              # New function
              if [ -z "$changed_functions" ]; then
                changed_functions="./$(echo $func_name | sed 's/-/\//g').f.ts"
              else
                changed_functions="$changed_functions ./$(echo $func_name | sed 's/-/\//g').f.ts"
              fi
            fi
          done
          
          echo "functions=$changed_functions" >> $GITHUB_OUTPUT
          echo "has_changes=$([[ -n "$changed_functions" ]] && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT

      - name: Deploy changed functions (Production)
        if: github.ref == 'refs/heads/main' && steps.detect-changes.outputs.has_changes == 'true'
        run: npm run functions:deploy:production -- ${{ steps.detect-changes.outputs.functions }}

      - name: Deploy changed functions (Development)
        if: github.ref == 'refs/heads/develop' && steps.detect-changes.outputs.has_changes == 'true'
        run: npm run functions:deploy -- ${{ steps.detect-changes.outputs.functions }} 
